AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-Type, Authorization'"
      AllowOrigin: "'*'"
Resources:
  awssamfinal:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: crudfinal/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 300
      Events:
        getlead:
          Type: Api
          Properties:
            Path: /leads
            Method: get
        getonelead:
          Type: Api
          Properties:
            Path: /leads/{id}
            Method: get
        createlead:
          Type: Api
          Properties:
            Path: /leads
            Method: post
        updatelead:
          Type: Api
          Properties:
            Path: /leads/{id}
            Method: put
        deletelead:
          Type: Api
          Properties:
            Path: /leads/{id}
            Method: delete
        leadlog:
          Type: Api
          Properties:
            Path: /leads/{id}/log
            Method: get
        getcustomer:
          Type: Api
          Properties:
            Path: /customers
            Method: get
        getonecustomer:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: get
        updatecustomer:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: put
        deletecustomer:
          Type: Api
          Properties:
            Path: /customers/{id}
            Method: delete
        getuser:
          Type: Api
          Properties:
            Path: /users
            Method: get
        getone:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
        createuser:
          Type: Api
          Properties:
            Path: /users
            Method: post
        updateuser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: put
        deleteuser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: delete
        login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
        logout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post
        refresh:
          Type: Api
          Properties:
            Path: /auth/refresh
            Method: post
        createProd:
          Type: Api
          Properties:
            Path: /products
            Method: post
        getProd:
          Type: Api
          Properties:
            Path: /products
            Method: get
        getOneProd:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: get
        updateOneProd:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: put
        deleteOneProd:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: delete
      Environment:
        Variables:
          MONGODB_URI: mongodb+srv://khaikiwi:khaikiwi21@cluster0.vcoqi73.mongodb.net/?retryWrites=true&w=majority
          SECRET: secret
